### ISSUE TITLE
Some questions about PLAD dataset

### ISSUE THREAD

**Issue by zhengfeiyan** [andreluizbvs/PLAD#3]
Thanks for providing a piece of detailed power line assets dataset. However, I can't reach appropriate average precision when i use PLAD dataset. I find that you describe that you split in a standard 80/20 proportion for the training and test sets in the paper. And the dataset folder in github include two sub-folders named 20181127-A1 and 20181129-R. So i want to know whether 20181127-A1 is train sub-folder and 20181129-R is test subfolder.

If not, Can you send me a piece of exact dataset that have splited train and test sets? The following pictures introduce these problems.

**Comment by andreluizbvs** [comment]
Hello.

As we explain in the paper, we used Monte Carlo Cross-Validation, dividing the dataset into five different train and test sets. I noticed that the labels are not in the README, I will add them there. Please, also find them attached here:

[labels.zip](https://github.com/andreluizbvs/PLAD/files/8952243/labels.zip)

**Comment by yuyyuu** [comment]
Thanks for your work. I have a question. Does the bbox represent [x,  y, weight, height]?

**Comment by andreluizbvs** [comment]
The bbox represents [x_top_left, y_top_left, width, height].

'top_left' refers to the top left point of the bbox.

So, the bottom right point is (x_top_left + width, y_top_left + height)
