### ISSUE TITLE
Question about the categories

### ISSUE THREAD

**Issue by abtraore** [andreluizbvs/PLAD#4]
When I started parsing the dataset, I saw this in annotations.json (annotations['categories']):

 [{'supercategory': 'tower', 'id': 0, 'name': 'tower'}, {'supercategory': 'component', 'id': 1, 'name': 'insulator'}, {'supercategory': 'component', 'id': 2, 'name': 'spacer'}, {'supercategory': 'component', 'id': 3, 'name': 'damper'}, {'supercategory': 'component', 'id': 5, 'name': 'plate'}]

The IDs start at 0 and finish at 5 that's 6 classes, or we have 5 classes. This also extends to the annotations['images'].

I think it should be: 0,1,2,3,4 or probably I'm missing something...

Can you give me more clarification? Thanks.

BTW I downloaded the dataset from Google Drive.

**Comment by andreluizbvs** [comment]
Yes, you're correct; it should be '0,1,2,3,4...'. 
There was another class for ID 4, but we decided to drop it due to the small number of samples.
Anyway, there are 5 classes in total. Also, you shouldn't have major problems dealing with the id number skip.
